@xcopy /y /d /f "C:/WebKitOut/DerivedSources/JavaScriptCore/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKitOut/DerivedSources/JavaScriptCore/inspector/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/API/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/assembler/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/bindings/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/builtins/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/bytecode/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/debugger/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/dfg/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/disassembler/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/heap/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/inspector/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/interpreter/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/jit/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/llint/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/parser/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/profiler/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/replay/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/runtime/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/yarr/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/collector/handles/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/inspector/agents/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/inspector/augmentable/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
@xcopy /y /d /f "C:/Webkit2016/WebKit/Source/JavaScriptCore/inspector/remote/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/JavaScriptCore" >nul 2>nul
