/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(WEB_RTC)

#include "JSRTCRtpReceiver.h"

#include "JSDOMBinding.h"
#include "JSDOMConstructor.h"
#include "JSDOMConvert.h"
#include "JSMediaStreamTrack.h"
#include <runtime/FunctionPrototype.h>
#include <wtf/GetPtr.h>

using namespace JSC;

namespace WebCore {

// Attributes

JSC::EncodedJSValue jsRTCRtpReceiverTrack(JSC::ExecState*, JSC::EncodedJSValue, JSC::PropertyName);
JSC::EncodedJSValue jsRTCRtpReceiverConstructor(JSC::ExecState*, JSC::EncodedJSValue, JSC::PropertyName);
bool setJSRTCRtpReceiverConstructor(JSC::ExecState*, JSC::EncodedJSValue, JSC::EncodedJSValue);

class JSRTCRtpReceiverPrototype : public JSC::JSNonFinalObject {
public:
    using Base = JSC::JSNonFinalObject;
    static JSRTCRtpReceiverPrototype* create(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::Structure* structure)
    {
        JSRTCRtpReceiverPrototype* ptr = new (NotNull, JSC::allocateCell<JSRTCRtpReceiverPrototype>(vm.heap)) JSRTCRtpReceiverPrototype(vm, globalObject, structure);
        ptr->finishCreation(vm);
        return ptr;
    }

    DECLARE_INFO;
    static JSC::Structure* createStructure(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(vm, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), info());
    }

private:
    JSRTCRtpReceiverPrototype(JSC::VM& vm, JSC::JSGlobalObject*, JSC::Structure* structure)
        : JSC::JSNonFinalObject(vm, structure)
    {
    }

    void finishCreation(JSC::VM&);
};

using JSRTCRtpReceiverConstructor = JSDOMConstructorNotConstructable<JSRTCRtpReceiver>;

template<> JSValue JSRTCRtpReceiverConstructor::prototypeForStructure(JSC::VM& vm, const JSDOMGlobalObject& globalObject)
{
    UNUSED_PARAM(vm);
    return globalObject.functionPrototype();
}

template<> void JSRTCRtpReceiverConstructor::initializeProperties(VM& vm, JSDOMGlobalObject& globalObject)
{
    putDirect(vm, vm.propertyNames->prototype, JSRTCRtpReceiver::prototype(vm, &globalObject), DontDelete | ReadOnly | DontEnum);
    putDirect(vm, vm.propertyNames->name, jsNontrivialString(&vm, String(ASCIILiteral("RTCRtpReceiver"))), ReadOnly | DontEnum);
    putDirect(vm, vm.propertyNames->length, jsNumber(0), ReadOnly | DontEnum);
}

template<> const ClassInfo JSRTCRtpReceiverConstructor::s_info = { "RTCRtpReceiver", &Base::s_info, 0, CREATE_METHOD_TABLE(JSRTCRtpReceiverConstructor) };

/* Hash table for prototype */

static const HashTableValue JSRTCRtpReceiverPrototypeTableValues[] =
{
    { "constructor", DontEnum, NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsRTCRtpReceiverConstructor), (intptr_t) static_cast<PutPropertySlot::PutValueFunc>(setJSRTCRtpReceiverConstructor) } },
    { "track", ReadOnly | CustomAccessor, NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsRTCRtpReceiverTrack), (intptr_t) static_cast<PutPropertySlot::PutValueFunc>(0) } },
};

const ClassInfo JSRTCRtpReceiverPrototype::s_info = { "RTCRtpReceiverPrototype", &Base::s_info, 0, CREATE_METHOD_TABLE(JSRTCRtpReceiverPrototype) };

void JSRTCRtpReceiverPrototype::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    reifyStaticProperties(vm, JSRTCRtpReceiverPrototypeTableValues, *this);
}

const ClassInfo JSRTCRtpReceiver::s_info = { "RTCRtpReceiver", &Base::s_info, 0, CREATE_METHOD_TABLE(JSRTCRtpReceiver) };

JSRTCRtpReceiver::JSRTCRtpReceiver(Structure* structure, JSDOMGlobalObject& globalObject, Ref<RTCRtpReceiver>&& impl)
    : JSDOMWrapper<RTCRtpReceiver>(structure, globalObject, WTFMove(impl))
{
}

void JSRTCRtpReceiver::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    ASSERT(inherits(info()));

}

JSObject* JSRTCRtpReceiver::createPrototype(VM& vm, JSGlobalObject* globalObject)
{
    return JSRTCRtpReceiverPrototype::create(vm, globalObject, JSRTCRtpReceiverPrototype::createStructure(vm, globalObject, globalObject->objectPrototype()));
}

JSObject* JSRTCRtpReceiver::prototype(VM& vm, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSRTCRtpReceiver>(vm, globalObject);
}

void JSRTCRtpReceiver::destroy(JSC::JSCell* cell)
{
    JSRTCRtpReceiver* thisObject = static_cast<JSRTCRtpReceiver*>(cell);
    thisObject->JSRTCRtpReceiver::~JSRTCRtpReceiver();
}

template<> inline JSRTCRtpReceiver* BindingCaller<JSRTCRtpReceiver>::castForAttribute(ExecState&, EncodedJSValue thisValue)
{
    return jsDynamicDowncast<JSRTCRtpReceiver*>(JSValue::decode(thisValue));
}

static inline JSValue jsRTCRtpReceiverTrackGetter(ExecState&, JSRTCRtpReceiver&, ThrowScope& throwScope);

EncodedJSValue jsRTCRtpReceiverTrack(ExecState* state, EncodedJSValue thisValue, PropertyName)
{
    return BindingCaller<JSRTCRtpReceiver>::attribute<jsRTCRtpReceiverTrackGetter>(state, thisValue, "track");
}

static inline JSValue jsRTCRtpReceiverTrackGetter(ExecState& state, JSRTCRtpReceiver& thisObject, ThrowScope& throwScope)
{
    UNUSED_PARAM(throwScope);
    UNUSED_PARAM(state);
    auto& impl = thisObject.wrapped();
    JSValue result = toJS<IDLInterface<MediaStreamTrack>>(state, *thisObject.globalObject(), impl.track());
    return result;
}

EncodedJSValue jsRTCRtpReceiverConstructor(ExecState* state, EncodedJSValue thisValue, PropertyName)
{
    VM& vm = state->vm();
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    JSRTCRtpReceiverPrototype* domObject = jsDynamicDowncast<JSRTCRtpReceiverPrototype*>(JSValue::decode(thisValue));
    if (UNLIKELY(!domObject))
        return throwVMTypeError(state, throwScope);
    return JSValue::encode(JSRTCRtpReceiver::getConstructor(state->vm(), domObject->globalObject()));
}

bool setJSRTCRtpReceiverConstructor(ExecState* state, EncodedJSValue thisValue, EncodedJSValue encodedValue)
{
    VM& vm = state->vm();
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    JSValue value = JSValue::decode(encodedValue);
    JSRTCRtpReceiverPrototype* domObject = jsDynamicDowncast<JSRTCRtpReceiverPrototype*>(JSValue::decode(thisValue));
    if (UNLIKELY(!domObject)) {
        throwVMTypeError(state, throwScope);
        return false;
    }
    // Shadowing a built-in constructor
    return domObject->putDirect(state->vm(), state->propertyNames().constructor, value);
}

JSValue JSRTCRtpReceiver::getConstructor(VM& vm, const JSGlobalObject* globalObject)
{
    return getDOMConstructor<JSRTCRtpReceiverConstructor>(vm, *jsCast<const JSDOMGlobalObject*>(globalObject));
}

bool JSRTCRtpReceiverOwner::isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, SlotVisitor& visitor)
{
    UNUSED_PARAM(handle);
    UNUSED_PARAM(visitor);
    return false;
}

void JSRTCRtpReceiverOwner::finalize(JSC::Handle<JSC::Unknown> handle, void* context)
{
    auto* jsRTCRtpReceiver = static_cast<JSRTCRtpReceiver*>(handle.slot()->asCell());
    auto& world = *static_cast<DOMWrapperWorld*>(context);
    uncacheWrapper(world, &jsRTCRtpReceiver->wrapped(), jsRTCRtpReceiver);
}

#if ENABLE(BINDING_INTEGRITY)
#if PLATFORM(WIN)
#pragma warning(disable: 4483)
extern "C" { extern void (*const __identifier("??_7RTCRtpReceiver@WebCore@@6B@")[])(); }
#else
extern "C" { extern void* _ZTVN7WebCore14RTCRtpReceiverE[]; }
#endif
#endif

JSC::JSValue toJSNewlyCreated(JSC::ExecState*, JSDOMGlobalObject* globalObject, Ref<RTCRtpReceiver>&& impl)
{

#if ENABLE(BINDING_INTEGRITY)
    void* actualVTablePointer = *(reinterpret_cast<void**>(impl.ptr()));
#if PLATFORM(WIN)
    void* expectedVTablePointer = reinterpret_cast<void*>(__identifier("??_7RTCRtpReceiver@WebCore@@6B@"));
#else
    void* expectedVTablePointer = &_ZTVN7WebCore14RTCRtpReceiverE[2];
#if COMPILER(CLANG)
    // If this fails RTCRtpReceiver does not have a vtable, so you need to add the
    // ImplementationLacksVTable attribute to the interface definition
    static_assert(__is_polymorphic(RTCRtpReceiver), "RTCRtpReceiver is not polymorphic");
#endif
#endif
    // If you hit this assertion you either have a use after free bug, or
    // RTCRtpReceiver has subclasses. If RTCRtpReceiver has subclasses that get passed
    // to toJS() we currently require RTCRtpReceiver you to opt out of binding hardening
    // by adding the SkipVTableValidation attribute to the interface IDL definition
    RELEASE_ASSERT(actualVTablePointer == expectedVTablePointer);
#endif
    return createWrapper<RTCRtpReceiver>(globalObject, WTFMove(impl));
}

JSC::JSValue toJS(JSC::ExecState* state, JSDOMGlobalObject* globalObject, RTCRtpReceiver& impl)
{
    return wrap(state, globalObject, impl);
}

RTCRtpReceiver* JSRTCRtpReceiver::toWrapped(JSC::JSValue value)
{
    if (auto* wrapper = jsDynamicDowncast<JSRTCRtpReceiver*>(value))
        return &wrapper->wrapped();
    return nullptr;
}

}

#endif // ENABLE(WEB_RTC)
