@xcopy /y /s /d /f "C:/WebKit/WebKit/Source/WebCore/ForwardingHeaders/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/./*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/accessibility/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/bindings/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/bridge/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/contentextensions/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/css/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/dom/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/editing/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/fileapi/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/history/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/html/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/inspector/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/page/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/plugins/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/rendering/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/storage/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/style/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/svg/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/websockets/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/workers/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/xml/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/geolocation/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/indexeddb/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/websockets/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/indexeddb/client/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/indexeddb/legacy/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/indexeddb/server/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/indexeddb/shared/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/notifications/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/Modules/webdatabase/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/accessibility/win/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/bindings/js/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/bridge/c/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/bridge/jsc/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/css/parser/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/history/cf/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/html/forms/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/html/parser/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/html/shadow/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/html/track/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/appcache/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/archive/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/cache/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/icon/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/loader/archive/cf/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/page/animation/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/page/csp/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/page/scrolling/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/page/win/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/animation/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/audio/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/cf/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/mock/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/network/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/sql/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/text/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/win/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/cf/win/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/filters/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/opengl/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/opentype/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/texmap/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/transforms/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/win/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/mediastream/libwebrtc/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/text/transcoder/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/rendering/line/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/rendering/shapes/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/rendering/style/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/rendering/svg/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/svg/animation/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/svg/graphics/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/svg/properties/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/svg/graphics/filters/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/graphics/cairo/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
@xcopy /y /d /f "C:/WebKit/WebKit/Source/WebCore/platform/network/curl/*.h" "C:/WebKitOut/DerivedSources/ForwardingHeaders/WebCore" >nul 2>nul
