partial interface WorkerGlobalScope {
    [Conditional=FETCH_API, EnabledAtRuntime=FetchAPI, PrivateIdentifier, PublicIdentifier] attribute FetchHeadersConstructor Headers;
    [Conditional=FETCH_API, EnabledAtRuntime=FetchAPI, PrivateIdentifier, PublicIdentifier] attribute FetchRequestConstructor Request;
    [Conditional=FETCH_API, EnabledAtRuntime=FetchAPI, PrivateIdentifier, PublicIdentifier] attribute FetchResponseConstructor Response;
    [Conditional=READABLE_STREAM_API|WRITABLE_STREAM_API] attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    [Conditional=READABLE_STREAM_API|WRITABLE_STREAM_API] attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [Conditional=READABLE_STREAM_API, PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [Conditional=WEB_SOCKETS, EnabledAtRuntime] attribute WebSocketConstructor WebSocket;
    [Conditional=SUBTLE_CRYPTO] attribute CryptoKeyConstructor CryptoKey;
    [Conditional=SUBTLE_CRYPTO] attribute SubtleCryptoConstructor SubtleCrypto;
    attribute DOMCoreExceptionConstructor DOMException;
    attribute DOMPointConstructor DOMPoint;
    attribute DOMPointReadOnlyConstructor DOMPointReadOnly;
    attribute DOMRectConstructor DOMRect;
    attribute DOMRectReadOnlyConstructor DOMRectReadOnly;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    [Conditional=CHANNEL_MESSAGING] attribute MessageChannelConstructor MessageChannel;
    attribute MessageEventConstructor MessageEvent;
    attribute MessagePortConstructor MessagePort;
    attribute ProgressEventConstructor ProgressEvent;
    attribute TextDecoderConstructor TextDecoder;
    attribute TextEncoderConstructor TextEncoder;
    attribute BlobConstructor Blob;
    attribute FileReaderConstructor FileReader;
    attribute FileReaderSyncConstructor FileReaderSync;
    attribute DOMURLConstructor URL;
    attribute ImageDataConstructor ImageData;
    attribute URLSearchParamsConstructor URLSearchParams;
    attribute CryptoConstructor Crypto;
    attribute EventSourceConstructor EventSource;
    attribute WorkerNavigatorConstructor WorkerNavigator;
    attribute WorkerGlobalScopeConstructor WorkerGlobalScope;
    attribute WorkerLocationConstructor WorkerLocation;
    [PrivateIdentifier, PublicIdentifier] attribute XMLHttpRequestConstructor XMLHttpRequest;
    attribute XMLHttpRequestEventTargetConstructor XMLHttpRequestEventTarget;
};
